// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TypingLogic","status":true,"description":"Handles user typing logic.","parameters":{}},
{"name":"TypingWindows","status":true,"description":"Handles prompt windows for combat and bonuses.","parameters":{}},
{"name":"CombatLogic","status":true,"description":"Handles combat and enemy logic.","parameters":{}},
{"name":"GALV_EventSpawnerMZ","status":true,"description":"(v.1.2) Spawn events from a specified spawn map to a desired location.","parameters":{"mId":"2"}},
{"name":"CustomKeymap","status":true,"description":"Establishes a custom keymap.","parameters":{}}
];
