// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TypingLogic","status":true,"description":"Handles user typing logic.","parameters":{}},
{"name":"TypingWindows","status":true,"description":"Handles prompt windows for combat and bonuses.","parameters":{}}
];
