// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CombatLogic","status":true,"description":"Handles combat and enemy logic.","parameters":{}},
{"name":"TypingLogic","status":true,"description":"Handles user typing logic.","parameters":{}},
{"name":"TypingWindows","status":true,"description":"Handles prompt windows for combat and bonuses.","parameters":{}},
{"name":"TypingEnemyEvent","status":true,"description":"Creates the Game_Event subclass for typing enemies.","parameters":{}},
{"name":"GALV_EventSpawnerMZ","status":true,"description":"(v.1.2) Spawn events from a specified spawn map to a desired location.","parameters":{"mId":"2"}},
{"name":"CustomKeymap","status":true,"description":"Establishes a custom keymap.","parameters":{}},
{"name":"BetterShakeScreen","status":true,"description":"A better shake mechanic.","parameters":{}},
{"name":"PlayerLivesWindow","status":true,"description":"Creates a window showing the number of lives the player has.","parameters":{}},
{"name":"PlayerLogic","status":true,"description":"Extends the player class.","parameters":{}}
];
